controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

home:
    path: /
    controller: App\Controller\HomePageController::home


user:
    path: /user
    controller: App\Controller\UserController::profile

